import ReduxProvider from "../../store/store_provider";
import "../[locale]/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="gl"
      suppressHydrationWarning={true}
      suppressContentEditableWarning={true}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function() {
              const theme = localStorage.getItem("theme-mode") || "light";
              document.documentElement.className = theme;
            })();`,
          }}
        />
      </head>
      <ReduxProvider>
        <body>
          <div id="backdrop"></div>
          <div id="overlay"></div>
          <main>{children}</main>
        </body>
      </ReduxProvider>
    </html>
  );
}
